version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
            - run: docker build -t victortsaitw12/circleci_hello_world .
            - run: docker push victortsaitw12/circleci_hello_world