version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: sudo npm install -g
            - run: mkdir ~/junit
            - run:
                command: mocha test --reporter mocha-junit-reporter
                environment:
                  MOCHA_FILE: junit/test-results.xml
                when: always
            - store_test_results:
                path: ~/junit
            - store_artifacts:
                path: ~/junit
