version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: echo "hello world"
        deployment:
            hub:
                commands:
                    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
                    - docker push victortsaitw12/circleci_hello_world